# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: ./

jobs:
# Please do not rename this job
  build-project:
    name: build jobify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.x

      - name: Build Node assets
        env:
          CI: true
          CLOUD_API_KEY: 811361629584499
          CLOUD_API_SECRET: jDJB4N4mtelDuGJYklwqBY5VgBQ
          CLOUD_NAME: doo29rqxf
          JWT_EXPIRES_IN: 1d
          JWT_SECRET: secret
          MONGODB_URI: mongodb+srv://qcameron:Jahluv2305%21@cluster0.rsqj9h2.mongodb.net/Jobify?
          NODE_ENV: development
          PORT: 5100
          retryWrites: true&w=majority
          SITE_URL: ${{ inputs.site-url }}
        run: |
          node server
          npm install

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 6aa44a6f-2a47-4fd6-91ba-4887e213122d
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/jobify/config.yaml
          action: upload
